---
- hosts: masters
  become: yes
#  connection: local
  roles:
    - role: misc
#    - role: ssh
    - role: k8s-common
    - role: master
    - role: k8s-dashboard

- hosts: nodes
  become: yes
  roles:
    - role: misc
    - role: k8s-common
    - role: node


