---
- name: Join Kubernetes cluster
  become_user: root
  become: true
  become_method: sudo
  shell: kubeadm join c1-master1:6443 –token {{ hostvars['localhost']['k8s_token']['stdout'] }}  –discovery-token-ca-cert-hash sha256:{{ hostvars['localhost']['k8s_hash']['stdout'] }}

